services:
  postgres:
    container_name: bipa_postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: "local"
      POSTGRES_USER: "local"
      POSTGRES_DB: "local"
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U local" ]
      interval: 2s
      timeout: 5s
      retries: 10

  localstack:
    container_name: bipa_localstack
    image: localstack/localstack:3.0.2
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=secretsmanager
    volumes:
      - "./docker/localstack.sh:/etc/localstack/init/ready.d/aws-init.sh"
      - "./docker/localstack/secrets-manager-public.json:/etc/secrets-manager-public.json"
      - "./docker/localstack/secrets-manager-sensitive.json:/etc/secrets-manager-sensitive.json"

volumes:
  postgres_data: