apiVersion: v1
kind: Service
metadata:
  name: bipa-api
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: bipa-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bipa-api
spec:
  selector:
    matchLabels:
      app: bipa-api
  template:
    metadata:
      labels:
        app: bipa-api
    spec:
      containers:
        - name: api
          image: bipa-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: bipa-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bipa-worker
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: bipa-worker
        spec:
          containers:
            - name: worker
              image: bipa-worker:latest
              imagePullPolicy: Never
              envFrom:
                - configMapRef:
                    name: bipa-config
          restartPolicy: OnFailure
